/**
 * Devnet setup script — calls initialize_config and start_season
 * so the oracle can begin driving rounds.
 *
 * Usage: npx tsx scripts/devnet-setup.ts [options]
 *
 * Options:
 *   --season N       Season number to initialize (default: 1)
 *   --grid WxH       Grid dimensions (default: 10x10)
 *   --fund-oracle    Airdrop 2 SOL to oracle wallet on devnet before setup
 *   --help           Print this usage message and exit
 *
 * Requires oracle/.env to be configured with:
 *   SOLANA_RPC_URL, ORACLE_KEYPAIR, PROGRAM_ID
 */

import * as dotenv from "dotenv";
import * as anchor from "@coral-xyz/anchor";
import { Connection, Keypair, PublicKey, SystemProgram } from "@solana/web3.js";
import * as path from "path";
import { execSync } from "child_process";

// Load env from oracle/.env
dotenv.config({ path: path.resolve(__dirname, "../oracle/.env") });

// ---------------------------------------------------------------------------
// Argument parsing
// ---------------------------------------------------------------------------

function parseArgs() {
  const args = process.argv.slice(2);

  if (args.includes("--help") || args.includes("-h")) {
    console.log(`
Usage: npx tsx scripts/devnet-setup.ts [options]

Options:
  --season N       Season number to initialize (default: 1)
  --grid WxH       Grid dimensions e.g. 10x10 (default: 10x10)
  --fund-oracle    Airdrop 2 SOL to oracle wallet before setup
  --help           Print this usage message and exit

Examples:
  npx tsx scripts/devnet-setup.ts
  npx tsx scripts/devnet-setup.ts --season 2 --grid 20x20
  npx tsx scripts/devnet-setup.ts --season 1 --fund-oracle
`.trim());
    process.exit(0);
  }

  let seasonNumber = 1;
  let gridWidth = 10;
  let gridHeight = 10;
  let fundOracle = false;

  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--season" && args[i + 1]) {
      const n = parseInt(args[i + 1], 10);
      if (isNaN(n) || n < 1) {
        console.error("--season must be a positive integer");
        process.exit(1);
      }
      seasonNumber = n;
      i++;
    } else if (args[i] === "--grid" && args[i + 1]) {
      const parts = args[i + 1].split("x");
      if (parts.length !== 2) {
        console.error("--grid must be in WxH format, e.g. 10x10");
        process.exit(1);
      }
      gridWidth = parseInt(parts[0], 10);
      gridHeight = parseInt(parts[1], 10);
      if (isNaN(gridWidth) || isNaN(gridHeight) || gridWidth < 1 || gridHeight < 1) {
        console.error("--grid dimensions must be positive integers");
        process.exit(1);
      }
      i++;
    } else if (args[i] === "--fund-oracle") {
      fundOracle = true;
    } else {
      console.error(`Unknown argument: ${args[i]}\nRun with --help for usage.`);
      process.exit(1);
    }
  }

  return { seasonNumber, gridWidth, gridHeight, fundOracle };
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  const { seasonNumber, gridWidth, gridHeight, fundOracle } = parseArgs();

  // Validate required env vars
  const requiredVars = ["SOLANA_RPC_URL", "ORACLE_KEYPAIR", "PROGRAM_ID"];
  const missing = requiredVars.filter((k) => !process.env[k]);
  if (missing.length > 0) {
    console.error(`Missing env vars: ${missing.join(", ")}\nEnsure oracle/.env is configured.`);
    process.exit(1);
  }

  // Parse keypair (admin = oracle for devnet)
  const adminKeypair = Keypair.fromSecretKey(
    Uint8Array.from(JSON.parse(process.env.ORACLE_KEYPAIR!))
  );
  const programId = new PublicKey(process.env.PROGRAM_ID!);
  const rpcUrl = process.env.SOLANA_RPC_URL!;
  const connection = new Connection(rpcUrl, "confirmed");
  const wallet = new anchor.Wallet(adminKeypair);
  const provider = new anchor.AnchorProvider(connection, wallet, {
    commitment: "confirmed",
  });

  // Load IDL from oracle's local copy (generated by scripts/copy-idl.sh)
  const idl = require("../oracle/src/idl.json") as anchor.Idl;
  const program = new anchor.Program<anchor.Idl>(idl, provider);

  // ---------------------------------------------------------------------------
  // Optional: fund oracle wallet via airdrop
  // ---------------------------------------------------------------------------
  if (fundOracle) {
    console.log(`Funding oracle wallet ${adminKeypair.publicKey.toBase58()} with 2 SOL...`);
    try {
      execSync(
        `solana airdrop 2 ${adminKeypair.publicKey.toBase58()} --url ${rpcUrl}`,
        { stdio: "inherit" }
      );
      console.log("Airdrop successful.");
    } catch (err) {
      console.warn("Airdrop failed (may be rate-limited). Continuing...");
    }
  }

  // ---------------------------------------------------------------------------
  // Derive PDAs
  // ---------------------------------------------------------------------------
  const [configPda] = PublicKey.findProgramAddressSync(
    [Buffer.from("config")],
    programId
  );

  const seasonBuf = Buffer.alloc(2);
  seasonBuf.writeUInt16LE(seasonNumber, 0);
  const [seasonPda] = PublicKey.findProgramAddressSync(
    [Buffer.from("season"), seasonBuf],
    programId
  );

  // ---------------------------------------------------------------------------
  // initialize_config (idempotent)
  // ---------------------------------------------------------------------------
  const configInfo = await connection.getAccountInfo(configPda);
  if (configInfo) {
    console.log("Config PDA already exists, skipping initialize_config.");
  } else {
    console.log("Calling initialize_config...");
    const tx1 = await program.methods
      .initializeConfig(adminKeypair.publicKey)
      .accounts({
        config: configPda,
        admin: adminKeypair.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .rpc();
    console.log("initialize_config tx:", tx1);
  }

  // ---------------------------------------------------------------------------
  // start_season (idempotent)
  // ---------------------------------------------------------------------------
  const seasonInfo = await connection.getAccountInfo(seasonPda);
  if (seasonInfo) {
    console.log(`Season ${seasonNumber} already exists, skipping start_season.`);
  } else {
    console.log(`Calling start_season (season=${seasonNumber}, grid=${gridWidth}x${gridHeight})...`);
    const tx2 = await program.methods
      .startSeason(seasonNumber, gridWidth, gridHeight)
      .accounts({
        seasonState: seasonPda,
        config: configPda,
        admin: adminKeypair.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .rpc();
    console.log("start_season tx:", tx2);
  }

  // ---------------------------------------------------------------------------
  // Summary
  // ---------------------------------------------------------------------------
  console.log(`
=== Devnet Setup Complete ===
Program ID:  ${programId.toBase58()}
Config PDA:  ${configPda.toBase58()}
Season PDA:  ${seasonPda.toBase58()}
Season:      ${seasonNumber}
Grid:        ${gridWidth}x${gridHeight}
Oracle:      ${adminKeypair.publicKey.toBase58()}

Next: Start the oracle with \`cd oracle && npm run dev\`
`);
}

main().catch((err) => {
  console.error("Setup failed:", err);
  process.exit(1);
});
